import React from 'react'
import useSWR from 'swr'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default async function Home() {
  /*
  const url = 'https://fantasy.premierleague.com/api/bootstrap-static/'

  const fetcher = (url) => fetch(url).then(res => res.json())
  const {data, error, isLoading} = useSWR(url, fetcher) */

  const res = await fetch('https://fantasy.premierleague.com/api/bootstrap-static/')
  const responseData = res.json()

  const teamData = await Promise.all([responseData]);

  console.log(teamData)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Fantasy Premier League Clone </h1>
        <div id="points-container" className={styles.pointsContainer}>
            <p>This is a points container </p>
            <div id="points-information" className={styles.pointsInformation}> 
              <p>Final Points </p>
              <p>Transfers </p>
            </div>
        </div>
      </main>
    </>
  )
}
